version: '3.1'
services:
  ngnix:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - D:/app/dockervolumes/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - D:/app/dockervolumes/nginx/conf.d:/etc/nginx/conf.d
      - D:/app/dockervolumes/nginx/conf/cors_params:/etc/nginx/conf/cors_params
      - D:/app/dockervolumes/nginx/logs:/var/log/nginx/
      - D:/app/dockervolumes/nginx/html:/usr/share/nginx/html