cassandra.contactPoints=cassandra
# cassandra.username=cassandra
# cassandra.password=cassandra
cassandra.keyspace=glowroot
cassandra.consistencyLevel=QUORUM
# agent监听地址，0.0.0.0允许外部agent接入
grpc.bindAddress=0.0.0.0
grpc.port=8181
web.bindAddress=0.0.0.0
web.port=4000