version: '3.9'
services:
  emqx:
    image: emqx/emqx:latest
    privileged: true
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8081:8081"
      - "18083:18083"
    #restart: unless-stopped
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8

  # admin public