version: '3.7'
services:
  filebrowser:
    image: 'filebrowser/filebrowser'
    container_name: "filebrowser"
    restart: unless-stopped
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
    ports:
      - '8088:80/tcp'
    volumes:
      - ./filebrowser/data:/srv
      - ./filebrowser/filebrowser.db:/filebrowser.db
      - ./filebrowser/filebrowser.json:/./filebrowser.json
      - /etc/localtime:/etc/localtime:ro