version: '3.7'
services:
  iserver:
    image: supermap/iserver:11.0.1
    container_name: iserver
    ports:
      - "8090:8090"
    volumes:
      - ./iserver/iserverOPTs:/opt/iserverOPTs
      - ./tmp:/tmp