version: '3'

services:
  zk1:
    container_name: zk1
    #hostname: zk1
    image: wurstmeister/zookeeper:latest
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=0.0.0.0:2888:3888,server.2=192.168.1.2:2888:3888,server.3=192.168.1.3:2888:3888
    volumes:
      - ./node1/zk_conf/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg:rw
      - ./node1/zk_data:/opt/zookeeper-3.4.13/data/:rw
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: wurstmeister/kafka:latest
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=192.168.3.42:2181,192.168.1.2:2181,192.168.1.3:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.3.42:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    ports:
      - 9092:9092