filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/*.log
  # multiline.pattern: '^\d{4}-\d{2}-\d{2}} \\d{2}:\\d{2}:\\d{2}.\\d{3}' # 正则表达式匹配日志开头的时间戳
  # multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
