version: '3.1'
services:
  nexus:
    #restart: always
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - 8081:8081
      - 5000:5000
    volumes:
      - ./nexus-data:/nexus-data


#http://127.0.0.1:8081/  admin   密码位置./nexus-data/admin.password