version: '2.1'
services:
#    gitlab:
#        image: gitlab/gitlab-ce:latest
#        network_mode: bridge
        #restart: always
        #ports:
        #  - 443:443
        #  - 80:80
        #  - 22:22
        #volumes:
        #  - gitlab_config:/etc/gitlab
        #  - gitlab_logs:/var/log/gitlab
        #  - gitlab_data:/var/opt/gitlab
    jenkins:
        image: jorgeacf/jenkins:2.121.3
        network_mode: bridge
        privileged: true
        #restart: always
        #ports:
        #  - 8080:8080
        volumes:
          - jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
    nexus:
        image: jorgeacf/nexus:3.13.0-01
        network_mode: bridge
        #restart: always
        #ports:
        #  - 8081:8081
#    sonar:
#        image: sonarqube
#        network_mode: bridge
        #restart: always
        #ports:
        #  - 9000:9000
        #  - 9092:9092

volumes:
  jenkins_home:
#  gitlab_config:
#  gitlab_logs:
#  gitlab_data: