version: "3"
services:
  mysql:
    image: mysql:5.7.36
    container_name: nacos-mysql5.7
    #command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1 --init-file /docker-entrypoint-initdb.d/nacos_config.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=nacos_config"
      - "TZ=Asia/Shanghai"
    volumes:
      - D:/app/dockervolumes/mysql/mydir:/mydir
      - D:/app/dockervolumes/mysql/datadir:/var/lib/mysql
      - D:/app/dockervolumes/mysql/conf/my.cnf:/etc/my.cnf
      # 初始化目录挂载
      - D:/app/dockervolumes/mysql/init/:/docker-entrypoint-initdb.d/
    ports:
      # 使用宿主机的3306端口映射到容器的3306端口
      # 宿主机：容器
      - 3306:3306
  # mysql8:
  #   image: mysql
  #   container_name: MySQL8
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --explicit_defaults_for_timestamp=true --lower_case_table_names=1
  #   volumes:
  #     - D:/app/dockervolumes/mysql/data:/var/lib/mysql
  #     - D:/app/dockervolumes/mysql/conf:/etc/mysql/conf.d
  #     - D:/app/dockervolumes/mysql/logs:/logs
  #     # 初始化目录挂载
  #     - D:/app/dockervolumes/mysql/init/:/docker-entrypoint-initdb.d/
  #   ports:
  #     - 3306:3306
