version: '3'
services:
  sentinel-dashboard:
    image: bladex/sentinel-dashboard
    container_name: sentinel-dashboard
    #restart: always
    environment:
      JAVA_OPTS: "-Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858 -Dproject.name=sentinel-dashboard"
    ports: #避免出现端口映射错误，建议采用字符串格式 8080端口为Dockerfile中EXPOSE端口
      - "8858:8858"
    volumes:
      - ./sentinel/logs:/root/logs

#http://127.0.0.1:8858  sentinel/sentinel