kind: pipeline
name: Dockerfiles build
steps:
  - name: test
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker ps -a

  - name: build image
    image: jorgeacf/make:latest
    commands:
      - cd ci/jenkins
      - make build
    when:
      branch:
        - develop
      event:
        - push
        - pull-request

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: github-drone-builds
      username: drone
    when:
      status: [ success, failure ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock