version: '2.2'
services:
    hive:
        image: jorgeacf/hive:2.3.3
        network_mode: bridge
        volumes:
            - hadoop_home:/opt/hadoop
        depends_on:
            - resource_manager
#    zeppelin:
#        image: jorgeacf/zeppelin:0.7.3
#        network_mode: bridge
#        volumes:
#            - hadoop_home:/opt/hadoop
#            - ~/.ssh:/home/zeppelin/.ssh:Z
#        depends_on:
#            - resource_manager
    zookeeper:
        image: jorgeacf/zookeeper:3.4.12
        #scale: 3
        network_mode: bridge
    mysql:
        image: jorgeacf/mysql:10.2.14
        network_mode: bridge
    nifi:
        image: jorgeacf/nifi:1.7.1
        network_mode: bridge
    nifi-registry:
        image: jorgeacf/nifi-registry:0.2.0
        volumes:
            - ~/.ssh:/home/nifi-registry/.ssh:Z
        network_mode: bridge
    resource_manager:
        image: jorgeacf/hadoop:2.9.1
        command: "/entrypoint-resource-manager.sh"
        network_mode: bridge
        volumes:
            - hadoop_home:/opt/hadoop
    datanode:
        image: jorgeacf/hadoop:2.9.1
        command: "/entrypoint-node-manager.sh"
        network_mode: bridge
volumes:
    hadoop_home: