version: '3.1'
services:
  wvp:
    build:  /
    #image: wvp
    container_name: wvp
    #restart: always
    privileged: true
    volumes:
      -  ./application-dev.yml:/app/application-dev.yml:rw
      -  ./logs/:/app/logs/:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 1
    ports:
      - 18088:18088
    #command: java -jar -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/heapdump.hprof -Duser.timezone=GMT+08 wvp.jar --spring.profiles.active=dev