version: '3.3'
services:
  aliyundrive-webdav:
    image: messense/aliyundrive-webdav:1.11
    container_name: aliyundrive-webdav
    volumes:
      - ./aliyundrive-webdav/:/etc/aliyundrive-webdav/
    restart: unless-stopped
    ports:
      - '8888:8080'
    environment:
      - 'REFRESH_TOKEN=50934a639ed54d75b480eef8d64da7fb'
      - 'read-buffer-size=10485760000000'

#http://127.0.0.1:8888/