version: '3.3'
services:
  aliyundrive-webdav:
    image: messense/aliyundrive-webdav
    container_name: aliyundrive-webdav
    volumes:
      - ./aliyundrive-webdav/:/etc/aliyundrive-webdav/
    restart: unless-stopped
    ports:
      - '8888:8080'
    environment:
      - 'REFRESH_TOKEN=7d529d18f6434074bf964d8a6e21469a'
      - 'read-buffer-size=10485760000000'

#http://127.0.0.1:8888/