version: '3'
services:
  clickhouse:
    #image: clickhouse/clickhouse-server:21.3
    image: clickhouse/clickhouse-server:latest
    privileged: true
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouseroot
    # volumes:
    #   - D:/custom/docker/data/clickhouse/data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
          
  filebeat:
    image: elastic/filebeat:7.10.1
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./clickhouse/log:/usr/share/filebeat/log
      - ./clickhouse/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    user: root
    command: filebeat -e -strict.perms=false