services:
  opensearch:
    hostname: opensearch
    image: opensearchproject/opensearch:3.7.0
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - node.name=opensearch # Name the node that will run in this container
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables security plugin
    healthcheck:
      test: "curl --fail http://localhost:9200 || exit 1"
      interval: 1s
      timeout: 1s
      retries: 60
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - "9200:9200" # REST API
      - "9600:9600" # Performance Analyzer
    deploy:
      resources:
        limits:
          memory: 1280M
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:3.7.0
    ports:
      - "5601:5601"
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
    depends_on:
      opensearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M

