services:
  opensearch:
    image: public.ecr.aws/opensearchproject/opensearch:3
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Opensearch@123456
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      # - DISABLE_SECURITY_PLUGIN=true
      # - DISABLE_INSTALL_DEMO_CONFIG=true
    privileged: true
    ports:
      - "9200:9200"
      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  opensearch-dashboards:
    image: public.ecr.aws/opensearchproject/opensearch-dashboards:3
    container_name: opensearch-dashboards
    privileged: true
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      # - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=none
      - server.host=0.0.0.0
    depends_on:
      - opensearch

# http://localhost:5601