version: '3.9'
services:
  zlmediakit:
    image: 89e876ac9dd2
    container_name: zlmediakit
    #restart: always
    privileged: true
    volumes:
      -  ./config.ini:/opt/media/conf/config.ini
      -  ../www:/opt/media/bin/www:rw
      -  ./log:/opt/media/log
    ports:
      - 11935:1935
      - 18080:80
      - 8443:443
      - 8554:554
      - 10000:10000
      - 10000:10000/udp
      - 8000:8000/udp
      - 9000:9000/udp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: 3