version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: node1
    container_name: rabbitmq1
    #restart: always
    environment:
      ERLANG-COOKIE: rabbitmqcluster
    ports:
     - "15672:15672"
     - "25672:25672"
     - "4369:4369"
     - "5671:5671"
     - "5672:5672"
    volumes:
     - ./rabbitmq/data:/var/lib/rabbitmq
     - ./rabbitmq/hosts:/etc/hosts
     - ./rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
