version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    hostname: rabbit
    container_name: rabbitmq
    #restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq3/data:/var/lib/rabbitmq3
      - ./rabbitmq3/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

