version: "3.8"
services:
  rabbitmq1:
    image: rabbitmq:3.9-management
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G
      # restart_policy:
      #   condition: any
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: rabbitmq1
    container_name: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - ./rabbitmq1/data:/var/lib/rabbitmq3
      - ./rabbitmq1/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      # - ./rabbitmq3/etc/localtime:/etc/localtime

  rabbitmq2:
    image: rabbitmq:3.9-management
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G
      # restart_policy:
      #   condition: any
    ports:
      - "5673:5672"
    hostname: rabbitmq2
    container_name: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - ./rabbitmq2/data:/var/lib/rabbitmq3
      - ./rabbitmq2/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      # - ./rabbitmq3/etc/localtime:/etc/localtime

  rabbitmq3:
    image: rabbitmq:3.9-management
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 8G
      # restart_policy:
      #   condition: any
    ports:
      - "5674:5672"
    hostname: rabbitmq3
    container_name: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - ./rabbitmq3/data:/var/lib/rabbitmq3
      - ./rabbitmq3/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      # - ./rabbitmq3/etc/localtime:/etc/localtime


#docker-compose --compatibility -f rabbitmq-compose.yml up -d